import Head from 'next/head';
import Image from 'next/image';

import Header from '../src/Header/Header';
import HeroSection from '../src/HeroSection/HeroSection';
import TruckImage from '../src/TruckImage/TruckImage';

export default function Home() {
	return (
		<>
			<Head>
				<title>The Classic Truck</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Header />
			<HeroSection />
			<TruckImage />
		</>
	);
}
